### ISSUE TITLE
something broke

### ISSUE THREAD

**Issue by ghost** [dai-shi/es-beautifier#20]
[Enter steps to reproduce:]

1. use on an HTML file
2. error

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [es-beautifier](https://github.com/dai-shi/es-beautifier.git#atom) package 1.1.0-atom

### Stack Trace

Uncaught Error: spawnSync node ENOENT

```
At child_process.js:657

Error: spawnSync node ENOENT
    at Object.spawnSync (internal/child_process.js:1018:20)
    at spawnSync (child_process.js:621:24)
    at execFileSync (child_process.js:649:15)
    at func (electron/js2c/asar.js:138:31)
    at execCLI (/packages/es-beautifier/index.js:9:10)
    at HTMLElement.beautify (/packages/es-beautifier/index.js:20:24)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:349780)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:683764)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:855324)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:853266)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:852256)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:856344)
```

### Commands

```
     -6:03.3.0 core:save (input.hidden-input)
     -5:25.1.0 editor:newline (input.hidden-input)
     -5:24.7.0 core:paste (input.hidden-input)
     -5:21.9.0 core:backspace (input.hidden-input)
     -5:20.2.0 core:save (input.hidden-input)
     -4:45.7.0 core:paste (input.hidden-input)
     -4:43.2.0 core:save (input.hidden-input)
     -3:29.2.0 command-palette:toggle (div.tool-panel.tree-view)
  2x -3:21.4.0 tree-view:toggle (div.tool-panel.tree-view)
     -3:10.2.0 styleguide:show (div.tool-panel.tree-view)
  2x -1:11.5.0 find-and-replace:use-selection-as-find-pattern (input.hidden-input)
     -0:38 command-palette:toggle (input.hidden-input)
     -0:32.2.0 core:backspace (input.hidden-input)
     -0:30.9.0 es-beautifier (input.hidden-input)
     -0:08.2.0 command-palette:toggle (input.hidden-input)
     -0:05.5.0 es-beautifier (input.hidden-input)
```

### Non-Core Packages

```
es-beautifier 1.1.0-atom 
```

**Comment by ghost** [comment]
im stupid
